env:
  browser: true
  node: true
  es2021: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - next
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - react
  - '@typescript-eslint'
  - import
  - prettier
rules:

  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  import/newline-after-import:
    - error
    - count: 1
  "@typescript-eslint/no-explicit-any": "error"
  "@typescript-eslint/no-unused-vars": "error"
  no-duplicate-imports: 'error'
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 0
  prettier/prettier:
    - error
    - endOfLine: auto
      semi: false
      trailingComma: "all"
      singleQuote: false
      bracketSpacing: true
      bracketSameLine: false
  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: true


    